version: '3'
services:
  mongo:
    image: mongo
  backend:
    image: student-wiki-api
    build: ./backend/student-wiki-api
    environment:
      - MONGO=mongo
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
  frontend:
    image: student-wiki
    build: ./frontend/student-wiki
    ports:
      - "80:80"


